### ISSUE TITLE
Could the ego car be the scene center?

### ISSUE THREAD

**Issue by GANWANSHUI** [aharley/bev_baseline#3]
Hi, thanks a lot for sharing the nice work. I am wondering whether the ego car could be the scene center as the BEVFormer defined. It seems that the current center is defined in the front camera.

 And another tiny question is that, in the code, there have some customized operations such as:
merge_intrinsics, split_intrinsics, safe_inverse.
I am wondering that would it cut down the performance if used common libraries such as PyTorch and NumPy, like torch.inverse()， np.linalg.inv().

Thanks again!

**Comment by aharley** [comment]
Yes, the `scene_centroid` parameter in `vox_util` defines the centroid of the 3D/BEV coordinate system, so you can shift that around as you like. 

Those merge/split functions don't really do anything computational, they just slice and concatenate. 

I like `safe_inverse` because it takes advantage of the fact that the 4x4 matrix is a rigid transformation, and guarantees that the output is rigid also, whereas the basic torch/numpy inverse ops don't assume anything and can occasionally do something unstable.

**Comment by GANWANSHUI** [comment]
I see. Thanks a lot!
